#!/usr/bin/env bash

# Find all changed files for this commit
# Compute the diff only once to save a small amount of time.
CHANGED_FILES=$(git diff --name-only --cached --diff-filter=ACMR)
# Get only changed files that match our file suffix pattern
get_pattern_files() {
    pattern=$(echo "$*" | sed "s/ /\$\\\|/g")
    echo "$CHANGED_FILES" | { grep "$pattern$" || true; }
}
# Get all changed python files
PY_FILES=$(get_pattern_files .py)
NOTEBOOKS=$(get_pattern_files .ipynb)

if [[ -n "$PY_FILES" ]]
then
    # Run black against changed python files for this commit
    if [[ -n "black --check $PY_FILES" ]]
    then
        black $PY_FILES
    else
        echo "black passes all altered python sources."
    fi

    # Run flake8 against changed python files for this commit
    if [[ -n "flake8 $PY_FILES" ]]
    then
        exit
    fi
fi

if [[ -n "$NOTEBOOKS" ]] then
    # Run black against changed notebooks for this commit
    if [[ -n "black --check $NOTEBOOKS" ]]
    then
        black $NOTEBOOKS
    else
        echo "black passes all altered notebooks."
    fi

    # Run flake8 against changed python files for this commit
    if [[ -n "nbqa flake8 $NOTEBOOKS" ]]
    then
        exit
    fi
fi
