#! /bin/bash
hyprctl dispach moveworkspacetomonitor "1 1"
hyprctl dispach moveworkspacetomonitor "2 0"
hyprctl dispach moveworkspacetomonitor "3 0"
hyprctl dispach moveworkspacetomonitor "4 0"
hyprctl dispach moveworkspacetomonitor "5 0"
hyprctl dispach moveworkspacetomonitor "6 0"
hyprctl dispach moveworkspacetomonitor "7 0"
hyprctl dispach moveworkspacetomonitor "8 0"
hyprctl dispach moveworkspacetomonitor "9 0"
hyprctl dispach moveworkspacetomonitor "10 0"
